version: '3.8'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: expense_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    image: mkashifaslam/expense-tracker-api:v1
    container_name: api-server
    depends_on:
      - postgres
    volumes:
      - api_data:/usr/src/app
    env_file:
      - .env
    ports:
      - "3005:3000"
  web:
    image: mkashifaslam/expense-tracker-web:v1
    container_name: webapp
    depends_on:
      - api
    volumes:
      - web_data:/usr/src/app
    env_file:
      - .env
    ports:
      - "9090:80"

volumes:
  postgres_data:
  api_data:
  web_data:
