version: '3.8'

services:

  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cassbana123
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
 mysql: